import asyncio
import os
import shutil
import logging
from typing import Optional
from aegisos.core.protocol import AACPMessage, AACPIntent
from aegisos.core.workspace import WorkspaceManager
from aegisos.core.dispatcher import AegisDispatcher
from aegisos.agents.stub import StubAgent

# 配置日志
logging.basicConfig(level=logging.INFO, format='%(name)s: %(message)s')
logger = logging.getLogger("E2E_Test")

class E2ECoderLogic:
    """封装原本在 DummyCoderAgent 中的测试逻辑"""
    def __init__(self, agent_id: str, dispatcher: AegisDispatcher, workspace: WorkspaceManager):
        self.agent_id = agent_id
        self.dispatcher = dispatcher
        self.workspace = workspace

    async def handle(self, message: AACPMessage):
        logger.info(f"[{self.agent_id}] Logic triggered by {message.sender}: {message.intent}")
        if message.intent == AACPIntent.TASK_COMPLETE and message.sender == "planner@local":
            # 1. 读取需求
            req_path = message.context_pointer
            req_content = await self.workspace.read_file(req_path)
            logger.info(f"[{self.agent_id}] Read requirement: {req_content}")
            
            # 2. “写代码”
            code_content = f"# Generated by {self.agent_id}\nprint('Hello from AegisOS')"
            code_path = await self.workspace.write_file("code.py", code_content)
            
            # 3. 回复 PM (planner)
            reply = AACPMessage(
                sender=self.agent_id,
                receiver="planner@local",
                intent=AACPIntent.INFORM,
                payload={"status": "Code is ready", "file": code_path}
            )
            await self.dispatcher.send_message(reply)

class DummyPMAgent:
    """扮演 Planner 角色的 PM Agent"""
    def __init__(self, agent_id: str, dispatcher: AegisDispatcher, workspace: WorkspaceManager):
        self.agent_id = agent_id
        self.dispatcher = dispatcher
        self.workspace = workspace
        self.coder_id: Optional[str] = None
        self.task_done = asyncio.Event()

    async def handle_message(self, message: AACPMessage):
        logger.info(f"[{self.agent_id}] Received message from {message.sender}: {message.intent}")
        
        # 处理系统回复的 SPAWN 成功
        if message.sender == "system@local" and message.intent == AACPIntent.INFORM:
            status = message.payload.get("status")
            if status == "SPAWNED":
                self.coder_id = message.payload.get("agent_id")
                logger.info(f"[{self.agent_id}] System spawned coder: {self.coder_id}")
                
                # 【关键 Hack】为了在 E2E 中给动态创建的 StubAgent 注入逻辑
                # 我们通过 Dispatcher 找到这个实例并替换它的 handle_message
                # 实际生产中，不同类型的 Agent 会有各自的类定义
                # 这里模拟的是：系统创建了一个基础代理，我们通过某种方式（如动态挂载技能）赋予它逻辑
                
                # 注意：在 Dispatcher 中 agents 存储的是回调函数
                # 我们需要通过闭包或者重新注册来注入逻辑
                coder_logic = E2ECoderLogic(self.coder_id, self.dispatcher, self.workspace)
                self.dispatcher.register_agent(self.coder_id, coder_logic.handle)
                
                # 触发任务开始
                asyncio.create_task(self.assign_task_to_coder())
            elif status == "TERMINATED":
                logger.info(f"[{self.agent_id}] System terminated coder: {message.payload.get('agent_id')}")
                self.task_done.set()

        # 处理 Coder 完成任务的回复
        elif message.sender == self.coder_id and message.intent == AACPIntent.INFORM:
            logger.info(f"[{self.agent_id}] Coder finished! Now asking system to terminate it.")
            # 销毁 Coder
            term_msg = AACPMessage(
                sender=self.agent_id,
                receiver="system@local",
                intent=AACPIntent.TERMINATE,
                payload={"agent_id": self.coder_id}
            )
            await self.dispatcher.send_message(term_msg)

    async def spawn_coder(self):
        """请求系统创建 Coder (类型为 stub)"""
        logger.info(f"[{self.agent_id}] Requesting system to spawn a temporary stub coder...")
        
        spawn_msg = AACPMessage(
            sender=self.agent_id,
            receiver="system@local",
            intent=AACPIntent.SPAWN,
            payload={
                "agent_type": "stub",
                "role": "coder",
                "agent_id": "coder_tmp_001@local"
            }
        )
        await self.dispatcher.send_message(spawn_msg)

    async def assign_task_to_coder(self):
        """给新创建的 Coder 分派任务"""
        logger.info(f"[{self.agent_id}] Assigning task to {self.coder_id}...")
        filepath = await self.workspace.write_file("req.txt", "Requirement: Stub Agent E2E test.")
        
        msg = AACPMessage(
            sender=self.agent_id,
            receiver=self.coder_id,
            intent=AACPIntent.TASK_COMPLETE,
            payload={"task": "do_it"},
            context_pointer=filepath
        )
        await self.dispatcher.send_message(msg)

async def main():
    # 初始化
    workspace_base = "_workspace_e2e"
    if os.path.exists(workspace_base):
        shutil.rmtree(workspace_base)
    workspace = WorkspaceManager(base_dir=workspace_base, session_id="stub-test")
    dispatcher = AegisDispatcher()
    
    # 初始化 Planner PM
    planner = DummyPMAgent("planner@local", dispatcher, workspace)
    dispatcher.register_agent(planner.agent_id, planner.handle_message)
    
    # 启动调度器
    await dispatcher.start()
    
    # 第一步：PM 申请创建一个 Coder (Stub 类型)
    await planner.spawn_coder()
    
    # 等待整个流程结束
    try:
        await asyncio.wait_for(planner.task_done.wait(), timeout=5.0)
        logger.info("E2E SUCCESS: Stub Agent Lifecycle & Logic verified.")
    except asyncio.TimeoutError:
        logger.error("E2E FAILED: Workflow timed out.")
    
    # 验证文件
    files = await workspace.list_files()
    logger.info(f"Final files in workspace: {files}")
    
    await dispatcher.stop()

if __name__ == "__main__":
    asyncio.run(main())
