import asyncio
import os
import shutil
import logging
from typing import Optional
from aegisos.core.protocol import AACPMessage, AACPIntent
from aegisos.core.workspace import WorkspaceManager
from aegisos.core.dispatcher import AegisDispatcher

# 配置日志
logging.basicConfig(level=logging.INFO, format='%(name)s: %(message)s')
logger = logging.getLogger("E2E_Test")

class DummyCoderAgent:
    """可动态实例化的 Coder Agent"""
    def __init__(self, agent_id: str, dispatcher: AegisDispatcher, workspace: WorkspaceManager):
        self.agent_id = agent_id
        self.dispatcher = dispatcher
        self.workspace = workspace

    async def handle_message(self, message: AACPMessage):
        logger.info(f"[{self.agent_id}] Received message from {message.sender}: {message.intent}")
        if message.intent == AACPIntent.TASK_COMPLETE and message.sender == "planner@local":
            # 1. 读取需求
            req_path = message.context_pointer
            req_content = await self.workspace.read_file(req_path)
            logger.info(f"[{self.agent_id}] Read requirement: {req_content}")
            
            # 2. “写代码”
            code_content = f"# Generated by {self.agent_id}\nprint('Hello from AegisOS')"
            code_path = await self.workspace.write_file("code.py", code_content)
            
            # 3. 回复 PM (planner)
            reply = AACPMessage(
                sender=self.agent_id,
                receiver="planner@local",
                intent=AACPIntent.INFORM,
                payload={"status": "Code is ready", "file": code_path}
            )
            await self.dispatcher.send_message(reply)

class DummyPMAgent:
    """扮演 Planner 角色的 PM Agent"""
    def __init__(self, agent_id: str, dispatcher: AegisDispatcher, workspace: WorkspaceManager):
        self.agent_id = agent_id
        self.dispatcher = dispatcher
        self.workspace = workspace
        self.coder_id: Optional[str] = None
        self.task_done = asyncio.Event()

    async def handle_message(self, message: AACPMessage):
        logger.info(f"[{self.agent_id}] Received message from {message.sender}: {message.intent}")
        
        # 处理系统回复的 SPAWN 成功
        if message.sender == "system@local" and message.intent == AACPIntent.INFORM:
            status = message.payload.get("status")
            if status == "SPAWNED":
                self.coder_id = message.payload.get("agent_id")
                logger.info(f"[{self.agent_id}] System spawned coder: {self.coder_id}")
                # 触发任务开始
                asyncio.create_task(self.assign_task_to_coder())
            elif status == "TERMINATED":
                logger.info(f"[{self.agent_id}] System terminated coder: {message.payload.get('agent_id')}")
                self.task_done.set()

        # 处理 Coder 完成任务的回复
        elif message.sender == self.coder_id and message.intent == AACPIntent.INFORM:
            logger.info(f"[{self.agent_id}] Coder finished! Now asking system to terminate it.")
            # 销毁 Coder
            term_msg = AACPMessage(
                sender=self.agent_id,
                receiver="system@local",
                intent=AACPIntent.TERMINATE,
                payload={"agent_id": self.coder_id}
            )
            await self.dispatcher.send_message(term_msg)

    async def spawn_coder(self):
        """请求系统创建 Coder"""
        logger.info(f"[{self.agent_id}] Requesting system to spawn a temporary coder...")
        
        # 在 MVP/E2E 阶段，我们将回调直接传给系统模拟实例化过程
        temp_coder_id = "coder_tmp_001@local"
        temp_coder = DummyCoderAgent(temp_coder_id, self.dispatcher, self.workspace)
        
        spawn_msg = AACPMessage(
            sender=self.agent_id,
            receiver="system@local",
            intent=AACPIntent.SPAWN,
            payload={
                "agent_id": temp_coder_id,
                "callback": temp_coder.handle_message  # 传递回调以模拟动态注册
            }
        )
        await self.dispatcher.send_message(spawn_msg)

    async def assign_task_to_coder(self):
        """给新创建的 Coder 分派任务"""
        logger.info(f"[{self.agent_id}] Assigning task to {self.coder_id}...")
        filepath = await self.workspace.write_file("req.txt", "Requirement: Dynamic creation test.")
        
        msg = AACPMessage(
            sender=self.agent_id,
            receiver=self.coder_id,
            intent=AACPIntent.TASK_COMPLETE, # 这里暂用 TASK_COMPLETE 表示需求交付
            payload={"task": "do_it"},
            context_pointer=filepath
        )
        await self.dispatcher.send_message(msg)

async def main():
    # 初始化
    workspace_base = "_workspace_e2e"
    if os.path.exists(workspace_base):
        shutil.rmtree(workspace_base)
    workspace = WorkspaceManager(base_dir=workspace_base, session_id="dynamic-test")
    dispatcher = AegisDispatcher()
    
    # 初始化 Planner PM
    planner = DummyPMAgent("planner@local", dispatcher, workspace)
    dispatcher.register_agent(planner.agent_id, planner.handle_message)
    
    # 启动调度器
    await dispatcher.start()
    
    # 第一步：PM 申请创建一个 Coder
    await planner.spawn_coder()
    
    # 等待整个流程结束 (Spawn -> Work -> Terminate)
    try:
        await asyncio.wait_for(planner.task_done.wait(), timeout=5.0)
        logger.info("E2E SUCCESS: Dynamic Agent Lifecycle verified.")
    except asyncio.TimeoutError:
        logger.error("E2E FAILED: Workflow timed out.")
    
    # 验证文件是否还在
    files = await workspace.list_files()
    logger.info(f"Final files in workspace: {files}")
    
    # 验证 Coder 是否已从调度器注销
    if "coder_tmp_001@local" not in dispatcher.agents:
        logger.info("E2E SUCCESS: Coder successfully unregistered from dispatcher.")
    else:
        logger.error("E2E FAILED: Coder still registered in dispatcher.")

    await dispatcher.stop()

if __name__ == "__main__":
    asyncio.run(main())
